### ISSUE TITLE
RC Release

### ISSUE THREAD

**Issue by xiaodong2008** [fastjs-team/core#127]
**Finally, we have scheduled the RC release** 🥰

## Todo List

- [ ] Feat
  - [ ] Plugin System
  - [ ] Cli
    - [ ] Default/Module scope 
    - [ ] Other selectable packages
- [ ] Refactor
  - [ ] `jsfast`
  - [ ] `@jsfast/core`
  - [ ] `@jsfast/dom`
  - [ ] `@jsfast/date`
  - [ ] `@jsfast/request`
  - [ ] `@jsfast/cookie`
  - [ ] `@jsfast/rand`
  - [ ] `@jsfast/copy`
- [ ] Documentation
  - [ ] Dom
  - [ ] Date
  - [ ] Request
  - [ ] Cookie
  - [ ] Utils
  - [ ] Cli
  - [ ] Plugin
- [ ] [Website](https://github.com/fastjs-team/core/issues/124)

**Comment by Inquerito** [comment]
I didn't understand the fourth line of the process

**Comment by Inquerito** [comment]
nice, keep being creative
